name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to check out and test (branch, tag, or SHA)"
        required: false
        default: "haiku"
      force-install:
        description: "Reinstall system disk, even when it was found in our cache"
        required: false
        default: false
        type: boolean

concurrency:
  group: haiku-build-and-test
  cancel-in-progress: true

env:
  HAIKU_NIGHTLY_VERSION: hrev59921
  PONY_LLVM_LIBS_HREV: hrev59861

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      VERSION: ${{ steps.buildsetup.outputs.VERSION }}
      PACKAGE: ${{ steps.buildsetup.outputs.PACKAGE }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v7

      - name: Get ponyc
        run: git clone --depth 1 --single-branch --branch ${{ inputs.ref || 'haiku' }} https://github.com/ahwayakchih/ponyc.git && ls -la

      - name: Create source for LIBS_TAG
        run: |
          echo $PONY_LLVM_LIBS_HREV >haiku_libs_tag.source
          sha256sum \
            ponyc/lib/CMakePresets.json \
            ponyc/CMakeLists.txt \
            ponyc/lib/CMakeLists.txt \
            ponyc/lib/build-libs.cmake \
            ponyc/lib/llvm/patches/* \
            >>haiku_libs_tag.source

      - name: Get Ponyc VERSION, prepare PACKAGE name
        id: buildsetup
        run: |
          export VERSION=$(cat ponyc/VERSION)
          echo version is $VERSION
          echo VERSION=$VERSION >> $GITHUB_OUTPUT
          git tag --sort=-version:refname
          export PACKAGE_REVISION=$(git tag --sort=-version:refname | grep $VERSION | head -n1 | cut -d '-' -f2 | xargs -I '{}' echo '{}+1' | bc || echo 1)
          echo revision is $PACKAGE_REVISION
          echo PACKAGE_REVISION=$PACKAGE_REVISION >> $GITHUB_OUTPUT

          echo PACKAGE=ponyc-$VERSION-$PACKAGE_REVISION-x86_64 >> $GITHUB_OUTPUT

      - name: self-test
        run: |
          echo VERSION=${{ steps.buildsetup.outputs.VERSION }}
          echo REVISION=${{ steps.buildsetup.outputs.PACKAGE_REVISION }}
          echo PACKAGE=${{ steps.buildsetup.outputs.PACKAGE }}
